#spring.application.name=job-micro-service
server:
  port: 8082

debug: false

spring:
  application:
    name: job-micro-service
  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: parjunb
    password: parjunb
#    url: jdbc:h2:mem:test
#  h2:
#    console:
#      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
# config server
  config:
    import:
      #- configserver:http://localhost:8888
      - optional:configserver:http://localhost:8888

# Eureka related
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/




# zipkin
management:
  tracing:
    sampling:
      probability: 1.0
