#spring.application.name=job-micro-service
server:
  port: 8082


spring:
  application:
    name: job-micro-service
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

