#spring.application.name=job-micro-service
server:
  port: 8082


spring:
  application:
    name: job-micro-service
  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: parjunb
    password: parjunb
#    url: jdbc:h2:mem:test
#  h2:
#    console:
#      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
