#spring.application.name=job-micro-service
server:
  port: 8082

job-service:
  url: http://job:8082
company-service:
  url: http://company:8081
review-service:
  url: http://review:8083



spring:
  application:
    name: job-micro-service
  datasource:
    url: jdbc:postgresql://postgres_container:5432/job
    username: parjunb
    password: parjunb
#    url: jdbc:h2:mem:test
#  h2:
#    console:
#      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
# config server
  config:
    import:
      #- configserver:http://localhost:8888
      - optional:configserver:http://config-server:8888

# Eureka related
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/




# zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans